export const tempFeedData: any[] = [    // Feed[]
    {
        id: 1,
        regDate: '2024-12-23T14:00:00Z',
        content: 'Exploring the beautiful streets of New York City!',
        writer: {
            id: 'john_doe',
            nickname: 'John Doe',
            profileImage: 'https://randomuser.me/api/portraits/men/1.jpg',
        },
        tags: ['travel', 'New York', 'city'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0'],
        address: 'New York, USA',
        x: 40.7128,
        y: -74.0060,
        viewCount: 1200,
        commentCount: 24,
        likeCount: 120,
        liked: true,
        commented: false
    },
    {
        id: 2,
        regDate: '2024-12-23T10:30:00Z',
        content: 'Had an amazing time visiting the Tower of London today.',
        writer: {
            id: 'jane_smith',
            nickname: 'Jane Smith',
            profileImage: 'https://randomuser.me/api/portraits/women/2.jpg',
        },
        tags: ['travel', 'London', 'landmarks'],
        mediaType: 'IMAGE',
        urls: [
            'https://images.unsplash.com/photo-1510270441230-ff9a5fc8aa92',
            'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0'
        ],
        address: 'London, UK',
        x: 51.5074,
        y: -0.1278,
        viewCount: 900,
        commentCount: 19,
        likeCount: 89,
        liked: false,
        commented: true
    },
    {
        id: 3,
        regDate: '2024-12-22T15:00:00Z',
        content: 'Surfing at Bondi Beach is an experience like no other!',
        writer: {
            id: 'robert_brown',
            nickname: 'Robert Brown',
            profileImage: 'https://randomuser.me/api/portraits/men/3.jpg',
        },
        tags: ['surfing', 'Bondi Beach', 'Australia'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1523413651479-597eb2da0ad6'],
        address: 'Bondi Beach, Australia',
        x: -33.8908,
        y: 151.2743,
        viewCount: 2000,
        commentCount: 56,
        likeCount: 234,
        liked: true,
        commented: true
    },
    {
        id: 4,
        regDate: '2024-12-21T18:00:00Z',
        content: 'The essence of true creativity lies not just in the ability to generate new and original ideas...',
        writer: {
            id: 'emily_white',
            nickname: 'Emily White',
            profileImage: 'https://randomuser.me/api/portraits/women/4.jpg',
        },
        tags: ['creativity', 'inspiration', 'art'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1527261834078-9b37d0ed2e5f'],
        address: 'Paris, France',
        x: 48.8566,
        y: 2.3522,
        viewCount: 1500,
        commentCount: 34,
        likeCount: 176,
        liked: false,
        commented: true
    },
    {
        id: 5,
        regDate: '2024-12-20T09:30:00Z',
        content: 'The cherry blossoms in Tokyo are breathtaking this time of year.',
        writer: {
            id: 'michael_lee',
            nickname: 'Michael Lee',
            profileImage: 'https://randomuser.me/api/portraits/men/5.jpg',
        },
        tags: ['cherry blossoms', 'Tokyo', 'nature'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1498654896293-37aacf113fd9'],
        address: 'Tokyo, Japan',
        x: 35.6762,
        y: 139.6503,
        viewCount: 2500,
        commentCount: 78,
        likeCount: 302,
        liked: true,
        commented: false
    },
    {
        id: 6,
        regDate: '2024-12-19T14:15:00Z',
        content: 'Cycling through the mountains of Switzerland is so peaceful.',
        writer: {
            id: 'anna_martin',
            nickname: 'Anna Martin',
            profileImage: 'https://randomuser.me/api/portraits/women/6.jpg',
        },
        tags: ['cycling', 'Switzerland', 'mountains'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0'],
        address: 'Swiss Alps, Switzerland',
        x: 46.8182,
        y: 8.2275,
        viewCount: 800,
        commentCount: 15,
        likeCount: 75,
        liked: false,
        commented: true
    },
    {
        id: 7,
        regDate: '2024-12-19T10:00:00Z',
        content: 'Enjoying the serenity of the Amazon rainforest.',
        writer: {
            id: 'lucas_jones',
            nickname: 'Lucas Jones',
            profileImage: 'https://randomuser.me/api/portraits/men/7.jpg',
        },
        tags: ['Amazon', 'rainforest', 'nature'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1516684669134-de6c127a2e4f'],
        address: 'Amazon Rainforest, Brazil',
        x: -3.4653,
        y: -62.2159,
        viewCount: 500,
        commentCount: 12,
        likeCount: 64,
        liked: true,
        commented: false
    },
    {
        id: 8,
        regDate: '2024-12-03T17:30:00Z',
        content: 'Witnessed the breathtaking northern lights last night!',
        writer: {
            id: 'sophie_clark',
            nickname: 'Sophie Clark',
            profileImage: 'https://randomuser.me/api/portraits/women/8.jpg',
        },
        tags: ['northern lights', 'Iceland', 'travel'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1549492424-3b37aa13938f'],
        address: 'Reykjavik, Iceland',
        x: 64.1355,
        y: -21.8954,
        viewCount: 700,
        commentCount: 20,
        likeCount: 90,
        liked: false,
        commented: true
    },
    {
        id: 9,
        regDate: '2024-11-18T11:45:00Z',
        content: 'Sunrise at the Grand Canyon is something everyone should experience.',
        writer: {
            id: 'daniel_taylor',
            nickname: 'Daniel Taylor',
            profileImage: 'https://randomuser.me/api/portraits/men/9.jpg',
        },
        tags: ['Grand Canyon', 'sunrise', 'USA'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb'],
        address: 'Grand Canyon, USA',
        x: 36.1069,
        y: -112.1129,
        viewCount: 1100,
        commentCount: 22,
        likeCount: 115,
        liked: true,
        commented: true
    },
    {
        id: 10,
        regDate: '2022-12-17T09:20:00Z',
        content: 'Learning pottery in a traditional Korean village.',
        writer: {
            id: 'mia_kim',
            nickname: 'Mia Kim',
            profileImage: 'https://randomuser.me/api/portraits/women/10.jpg',
        },
        tags: ['pottery', 'Korea', 'culture'],
        mediaType: 'IMAGE',
        urls: ['https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0'],
        address: 'Jeonju, South Korea',
        x: 35.8251,
        y: 127.1451,
        viewCount: 600,
        commentCount: 13,
        likeCount: 70,
        liked: false,
        commented: true
    }
];

// dummy
export const trandingComment = {
    profileImg: "https://via.placeholder.com/50",
    author: "John Doe",
    likes: 124,
    contents: "This is a sample comment. It provides an example of how a comment might look in the UI."
}